### ISSUE TITLE
docs: missing pages/topics tracker

### ISSUE THREAD

**Issue by s-makin** [canonical/ubuntu-pro-client#2685]
My analysis of the data from RTD up til end of July shows that the following topics are often searched for but don't have any results in our docs. These are the pages that we should add content on in order of popularity (with less popular but related search terms):

- [x] offline (air gapped, on prem) - [previously requested and in progress](https://github.com/canonical/ubuntu-pro-client/issues/2226)
- [ ] adsys (aad, onprem) - Explanation of how Pro interacts with AD/SAML integration and ID management tools
- [ ] esxi (vmware) - Explanation of how Pro works on VMs, how tokens are reused, etc

Tracking topics for future interest:
- [ ] certificate () - unclear if this is related to CA (since CA didn't appear as a search term) or certification. 
- [ ] general configuration (resolv_conf, sysctl.conf) - validation/examples might be useful

**Comment by orndorffgrant** [comment]
@s-makin are you still using this issue for tracking? We're not sure if the remaining items here are still valid or not.

**Comment by s-makin** [comment]
> @s-makin are you still using this issue for tracking? We're not sure if the remaining items here are still valid or not.

No I'm not, I'll close it!

**Comment by s-makin** [comment]
No longer using this issue for tracking, in favour of individual issues when they arise.
